name: Deploy React Projects to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout
      # -------------------------
      - name: Checkout
        uses: actions/checkout@v4


      # -------------------------
      # Node Setup
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      # =========================
      # TODO APP
      # =========================

      - name: Install TODO dependencies
        working-directory: TODO-APP
        run: npm ci

      - name: Build TODO App
        working-directory: TODO-APP
        run: npm run build


      # =========================
      # MOVIE EXPLORER
      # =========================

      - name: Install Movie Explorer dependencies
        working-directory: Movie-Explorer
        run: npm ci

      - name: Build Movie Explorer
        working-directory: Movie-Explorer
        env:
          VITE_OMDB_API_KEY: ${{ secrets.VITE_OMDB_API_KEY }}
        run: npm run build


      # =========================
      # CREATE FINAL WEBSITE
      # =========================

      - name: Prepare GitHub Pages
        run: |
          mkdir -p site/TODO-APP
          mkdir -p site/Movie-Explorer

          cp -r TODO-APP/dist/* site/TODO-APP/
          cp -r Movie-Explorer/dist/* site/Movie-Explorer/


      # -------------------------
      # GitHub Pages
      # -------------------------

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4